format = """
[](fg:mauve)\
$os\
$username\
[](bg:red fg:mauve)\
$directory\
[](fg:red bg:peach)\
$git_branch\
$git_status\
$git_metrics\
[](bg:blue fg:peach)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:blue)\
"""

# [](fg:#06969A)
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below

palette = 'mocha'

[palettes.mocha]
rosewater = '#f5e0dc'
flamingo = '#f22e7'
mauve = '#cba6f7'
red = '#f38ba8'
maroon = '#eba0ac'
peach = '#fab387'
yellow = '#f9e2af'
green = '#a6e3a1'
teal = '#94e2d5'
sky = '#89dceb'
sapphire = '#74c7ec'
blue = '#89b4fa'
lavender = '#b4befe'
text = '#cdd6f4'
subtext1 = '#bac2de'
subtext0 = '#a6adc8'
overlay2 = '#9399b2'
overlay1 = '#7f849c'
overlay0 = '#6c7086'
surface2 = '#585b70'
surface1 = '#45475a'
surface0 = '#313244'
base = '#1e1e2e'
mantle = '#181825'
crust = '#11111b'

[username]
show_always = true
style_user = "bg:mauve fg:base"
style_root = "bg:mauve fg:base"
format = '[$user]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E fg:base"
disabled = true # Disabled by default

[directory]
style = "bg:red fg:base"
format = "[$path]($style)"
truncation_length = 1
truncation_symbol = "  /"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"projects" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A fg:base"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "   "
style = "bg:peach fg:base"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:peach fg:base"
conflicted = '[=$count ](bg:peach fg:base)'
ahead = '[↑$count ](bg:peach fg:base)'
behind = '[↓$count ](bg:peach fg:base)'
modified = '[~$count ](bg:peach fg:base)'
staged = '[✔$count ](bg:peach fg:base)'
deleted = '[✘$count ](bg:peach fg:base)'
untracked = '[?$count ](bg:peach fg:base)'
format = '[$all_status$ahead_behind]($style)'

[golang]
symbol = " "
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A fg:base"
format = '[ ♥ $time ]($style)'
